### ISSUE TITLE
How do you get the "Maximum" possible TED ?

### ISSUE THREAD

**Issue by vsraptor** [JoaoFelipe/apted#4]
How do you get the "Maximum" possible TED ?

The TED is integer.
I want to get in some way the "maximum" TED between two trees.

The reason is I need a score with value between 0 and 1 i.e.  score = distance/max

Is this feasible ?

**Comment by vsraptor** [comment]
Is this a good way ?

```
nc1 = tree1.node_count()
nc2 = tree2.node_count()
score = ted /  max([nc1, nc2])

OR

similarity = 1 - (ted /  max([nc1, nc2]))


```

**Comment by JoaoFelipe** [comment]
I don't know how to get the actual maximum, but I would guess it should be something like `nc1 + nc2` instead of `max(nc1, nc2)`. If you have two completely distinct trees, the TED would probably be bigger than the size of one of them.
