### ISSUE TITLE
Question about how to normalize the tree edit distance

### ISSUE THREAD

**Issue by soloist97** [JoaoFelipe/apted#7]
Hi there

Thanks for your excellent repo!

My question is that if I want to normalize the computed tree edit distance into a certain range (e.g., between 0 and 1), what is the best way to do that? Or more mathematically, what is the upper bound of tree edit distance between arbitrary two trees?

Thanks in advance:)

**Comment by JoaoLages** [comment]
The way I do it is: `tree_edit_distance_between_source_and_target` / `tree_edit_distance_between_empty_source_and_target` 
I.e., normalizing by the TED with empty source
